# Docker Compose para desarrollo de la API Contable
version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: accounting_system_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d accounting_system_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Backend
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Configuración de ambiente
      ENVIRONMENT: development
      
      # Base de datos
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: accounting_system_dev
      DB_USER: postgres
      DB_PASSWORD: postgres_dev_password
      
      # JWT para desarrollo
      SECRET_KEY: "desarrollo-secret-key-no-usar-en-produccion"
      
      # Configuración para desarrollo
      DEBUG: "true"
      BACKEND_CORS_ORIGINS: '["http://localhost:3000","http://localhost:5173","http://localhost:8080"]'
      
      # Migraciones automáticas en desarrollo
      RUN_MIGRATIONS: "true"
      CREATE_ADMIN: "true"
      
      # Admin por defecto
      DEFAULT_ADMIN_EMAIL: "admin@contable.local"
      DEFAULT_ADMIN_PASSWORD: "DevAdmin123!"
      
    volumes:
      - ./app:/app/app:ro
      - ./alembic:/app/alembic:ro
      - ./.env.development:/app/.env.development:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
