# Docker Compose para desarrollo de la API Contable con IA
version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: contable_db
      POSTGRES_USER: contable_user
      POSTGRES_PASSWORD: contable_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contable_user -d contable_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Backend con servicios de IA
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Base de datos
      SQLALCHEMY_DATABASE_URI: "postgresql+asyncpg://contable_user:contable_password@postgres:5432/contable_db"
      
      # Configuración de la API
      DEBUG: "true"
      ENVIRONMENT: "development"
      
      # Token de Hugging Face (reemplazar con token real)
      HUGGINGFACE_API_TOKEN: "hf_exampletoken123"
      
      # Configuración de CORS
      BACKEND_CORS_ORIGINS: "http://localhost:3000,http://localhost:5173"
      
      # Configuración de seguridad
      SECRET_KEY: "your-secret-key-here"
      
    volumes:
      - ./app:/app/app:ro
      - ./alembic:/app/alembic:ro
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Esperando a que PostgreSQL esté listo...' &&
        sleep 10 &&
        echo 'Ejecutando migraciones...' &&
        alembic upgrade head &&
        echo 'Iniciando servidor...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data:
