"""add_unique_constraint_to_cost_center_name

Revision ID: 08f5bce446ef
Revises: 219968f9f601
Create Date: 2025-06-16 14:32:48.652038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f5bce446ef'
down_revision: Union[str, None] = '219968f9f601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cost_centers_name'), 'cost_centers', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_centers_name'), table_name='cost_centers')
    # ### end Alembic commands ###