"""Make descriptions optional in journal entries

Revision ID: 219968f9f601
Revises: 6ef75c262bfa
Create Date: 2025-06-15 20:32:02.093487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219968f9f601'
down_revision: Union[str, None] = '6ef75c262bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal_entries', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='Descripción del asiento (opcional, se genera automáticamente si no se proporciona)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal_entries', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               comment=None,
               existing_comment='Descripción del asiento (opcional, se genera automáticamente si no se proporciona)')
    # ### end Alembic commands ###