"""Add journal_id to payments table

Revision ID: 235cef43c172
Revises: 949eafb0e940
Create Date: 2025-07-02 13:37:47.714673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235cef43c172'
down_revision: Union[str, None] = '949eafb0e940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('journal_id', sa.UUID(), nullable=True, comment='Journal contable donde se registra el pago'))
    op.create_foreign_key(op.f('fk_payments_journal_id_journals'), 'payments', 'journals', ['journal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_payments_journal_id_journals'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'journal_id')
    # ### end Alembic commands ###