"""add_journal_id_to_invoices

Revision ID: 2ae2d2141f9e
Revises: 6e5322c8ec26
Create Date: 2025-06-23 11:40:48.938353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae2d2141f9e'
down_revision: Union[str, None] = '6e5322c8ec26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('journal_id', sa.UUID(), nullable=True, comment='Diario contable para la numeración de factura'))
    op.create_foreign_key(op.f('fk_invoices_journal_id_journals'), 'invoices', 'journals', ['journal_id'], ['id'])
    op.create_unique_constraint(op.f('uq_journals_sequence_prefix'), 'journals', ['sequence_prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_journals_sequence_prefix'), 'journals', type_='unique')
    op.drop_constraint(op.f('fk_invoices_journal_id_journals'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'journal_id')
    # ### end Alembic commands ###