"""Add Brazilian tax accounts to company settings

Revision ID: 495be228e719
Revises: add_default_sales_001
Create Date: 2025-07-06 15:54:42.062808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '495be228e719'
down_revision: Union[str, None] = 'add_default_sales_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add Brazilian tax account columns to company_settings
    op.add_column('company_settings', sa.Column('default_icms_payable_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para ICMS por pagar'))
    op.add_column('company_settings', sa.Column('default_icms_deductible_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para ICMS deducible'))
    op.add_column('company_settings', sa.Column('default_pis_payable_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para PIS por pagar'))
    op.add_column('company_settings', sa.Column('default_pis_deductible_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para PIS deducible'))
    op.add_column('company_settings', sa.Column('default_cofins_payable_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para COFINS por pagar'))
    op.add_column('company_settings', sa.Column('default_cofins_deductible_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para COFINS deducible'))
    op.add_column('company_settings', sa.Column('default_ipi_payable_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para IPI por pagar'))
    op.add_column('company_settings', sa.Column('default_ipi_deductible_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para IPI deducible'))
    op.add_column('company_settings', sa.Column('default_iss_payable_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para ISS por pagar'))
    op.add_column('company_settings', sa.Column('default_csll_payable_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para CSLL por pagar'))
    op.add_column('company_settings', sa.Column('default_irpj_payable_account_id', sa.UUID(), nullable=True, comment='Cuenta por defecto para IRPJ por pagar'))
    
    # Add foreign key constraints
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_icms_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_icms_deductible_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_pis_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_pis_deductible_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_cofins_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_cofins_deductible_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_ipi_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_ipi_deductible_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_iss_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_csll_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'company_settings', 'accounts', ['default_irpj_payable_account_id'], ['id'])
    
    # Journal updates
    op.alter_column('journals', 'default_debit_account_id',
               existing_type=sa.UUID(),
               comment='Cuenta débito por defecto para asientos automáticos',
               existing_nullable=True)
    op.alter_column('journals', 'default_credit_account_id',
               existing_type=sa.UUID(),
               comment='Cuenta crédito por defecto para asientos automáticos',
               existing_nullable=True)
    op.alter_column('journals', 'customer_receivable_account_id',
               existing_type=sa.UUID(),
               comment='Cuenta por cobrar clientes específica para este diario',
               existing_nullable=True)
    op.alter_column('journals', 'supplier_payable_account_id',
               existing_type=sa.UUID(),
               comment='Cuenta por pagar proveedores específica para este diario',
               existing_nullable=True)
    op.alter_column('journals', 'cash_difference_account_id',
               existing_type=sa.UUID(),
               comment='Cuenta para diferencias de caja/efectivo',
               existing_nullable=True)
    op.alter_column('journals', 'bank_charges_account_id',
               existing_type=sa.UUID(),
               comment='Cuenta para gastos y comisiones bancarias',
               existing_nullable=True)
    op.alter_column('journals', 'currency_exchange_account_id',
               existing_type=sa.UUID(),
               comment='Cuenta para diferencias de cambio de moneda',
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_journals_sequence_prefix'), 'journals', ['sequence_prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove Brazilian tax account columns
    op.drop_column('company_settings', 'default_irpj_payable_account_id')
    op.drop_column('company_settings', 'default_csll_payable_account_id')
    op.drop_column('company_settings', 'default_iss_payable_account_id')
    op.drop_column('company_settings', 'default_ipi_deductible_account_id')
    op.drop_column('company_settings', 'default_ipi_payable_account_id')
    op.drop_column('company_settings', 'default_cofins_deductible_account_id')
    op.drop_column('company_settings', 'default_cofins_payable_account_id')
    op.drop_column('company_settings', 'default_pis_deductible_account_id')
    op.drop_column('company_settings', 'default_pis_payable_account_id')
    op.drop_column('company_settings', 'default_icms_deductible_account_id')
    op.drop_column('company_settings', 'default_icms_payable_account_id')
    
    # Journal downgrades
    op.drop_constraint(op.f('uq_journals_sequence_prefix'), 'journals', type_='unique')
    op.alter_column('journals', 'currency_exchange_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Cuenta para diferencias de cambio de moneda',
               existing_nullable=True)
    op.alter_column('journals', 'bank_charges_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Cuenta para gastos y comisiones bancarias',
               existing_nullable=True)
    op.alter_column('journals', 'cash_difference_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Cuenta para diferencias de caja/efectivo',
               existing_nullable=True)
    op.alter_column('journals', 'supplier_payable_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Cuenta por pagar proveedores específica para este diario',
               existing_nullable=True)
    op.alter_column('journals', 'customer_receivable_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Cuenta por cobrar clientes específica para este diario',
               existing_nullable=True)
    op.alter_column('journals', 'default_credit_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Cuenta crédito por defecto para asientos automáticos',
               existing_nullable=True)
    op.alter_column('journals', 'default_debit_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Cuenta débito por defecto para asientos automáticos',
               existing_nullable=True)
    # ### end Alembic commands ###