"""add_nfe_tables_for_bulk_import

Revision ID: 51e58cbfdb4d
Revises: a9fb41079bc7
Create Date: 2025-06-25 14:14:44.202985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51e58cbfdb4d'
down_revision: Union[str, None] = 'a9fb41079bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_templates_id'), table_name='import_templates')
    op.drop_index(op.f('ix_import_templates_model'), table_name='import_templates')
    op.drop_index(op.f('ix_import_templates_name'), table_name='import_templates')
    op.drop_table('import_templates')
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='Código único del producto (se genera automáticamente si no se proporciona)',
               existing_comment='Código único del producto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='Código único del producto',
               existing_comment='Código único del producto (se genera automáticamente si no se proporciona)')
    op.create_table('import_templates',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('policy', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_import_templates_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_templates'))
    )
    op.create_index(op.f('ix_import_templates_name'), 'import_templates', ['name'], unique=False)
    op.create_index(op.f('ix_import_templates_model'), 'import_templates', ['model'], unique=False)
    op.create_index(op.f('ix_import_templates_id'), 'import_templates', ['id'], unique=False)
    # ### end Alembic commands ###