"""add_products_and_transaction_origin

Revision ID: 5276555e3ecf
Revises: be3cec477e27
Create Date: 2025-06-15 16:52:39.742363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5276555e3ecf'
down_revision: Union[str, None] = 'be3cec477e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('transaction_origin', sa.Enum('SALE', 'PURCHASE', 'ADJUSTMENT', 'TRANSFER', 'PAYMENT', 'COLLECTION', 'OPENING', 'CLOSING', 'OTHER', name='transactionorigin'), nullable=True, comment='Origen de la transacción (venta, compra, etc.)'))
    op.add_column('journal_entry_lines', sa.Column('product_id', sa.UUID(), nullable=True, comment='Producto asociado a esta línea'))
    op.add_column('journal_entry_lines', sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True, comment='Cantidad del producto'))
    op.add_column('journal_entry_lines', sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='Precio unitario del producto'))
    op.add_column('journal_entry_lines', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Porcentaje de descuento aplicado'))
    op.add_column('journal_entry_lines', sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Monto de descuento aplicado'))
    op.add_column('journal_entry_lines', sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Porcentaje de impuesto aplicado'))
    op.add_column('journal_entry_lines', sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Monto de impuesto aplicado'))
    op.create_foreign_key(op.f('fk_journal_entry_lines_product_id_products'), 'journal_entry_lines', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_journal_entry_lines_product_id_products'), 'journal_entry_lines', type_='foreignkey')
    op.drop_column('journal_entry_lines', 'tax_amount')
    op.drop_column('journal_entry_lines', 'tax_percentage')
    op.drop_column('journal_entry_lines', 'discount_amount')
    op.drop_column('journal_entry_lines', 'discount_percentage')
    op.drop_column('journal_entry_lines', 'unit_price')
    op.drop_column('journal_entry_lines', 'quantity')
    op.drop_column('journal_entry_lines', 'product_id')
    op.drop_column('journal_entries', 'transaction_origin')
    # ### end Alembic commands ###