"""add import template support

Revision ID: 622f005debcd
Revises: 2241f958e6ea
Create Date: 2025-06-24 00:28:11.364599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622f005debcd'
down_revision: Union[str, None] = '2241f958e6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_schedules', 'percentage',
               existing_type=sa.NUMERIC(precision=11, scale=6),
               comment=None,
               existing_comment='Porcentaje a pagar (hasta 6 decimales para mayor precisión)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_schedules', 'percentage',
               existing_type=sa.NUMERIC(precision=11, scale=6),
               comment='Porcentaje a pagar (hasta 6 decimales para mayor precisión)',
               existing_nullable=False)
    # ### end Alembic commands ###