"""Add journals table

Revision ID: 6e5322c8ec26
Revises: a7abd97d48c9
Create Date: 2025-06-23 11:13:01.635141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5322c8ec26'
down_revision: Union[str, None] = 'a7abd97d48c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre descriptivo del diario'),
    sa.Column('code', sa.String(length=10), nullable=False, comment='Código único del diario'),
    sa.Column('type', sa.Enum('SALE', 'PURCHASE', 'CASH', 'BANK', 'MISCELLANEOUS', name='journaltype'), nullable=False, comment='Tipo de diario (sale, purchase, cash, bank, miscellaneous)'),
    sa.Column('sequence_prefix', sa.String(length=10), nullable=False, comment='Prefijo único para la secuencia de numeración'),
    sa.Column('default_account_id', sa.UUID(), nullable=True, comment='Cuenta contable por defecto para asientos de este diario'),
    sa.Column('current_sequence_number', sa.Integer(), nullable=False, comment='Número actual de la secuencia'),
    sa.Column('sequence_padding', sa.Integer(), nullable=False, comment='Número de dígitos para rellenar con ceros (ej: 0001)'),
    sa.Column('include_year_in_sequence', sa.Boolean(), nullable=False, comment='Si incluir el año en la secuencia (ej: VEN/2025/0001)'),
    sa.Column('reset_sequence_yearly', sa.Boolean(), nullable=False, comment='Si resetear la secuencia cada año'),
    sa.Column('requires_validation', sa.Boolean(), nullable=False, comment='Si los asientos en este diario requieren validación'),
    sa.Column('allow_manual_entries', sa.Boolean(), nullable=False, comment='Si permite asientos manuales en este diario'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Si el diario está activo'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción del propósito del diario'),
    sa.Column('last_sequence_reset_year', sa.Integer(), nullable=True, comment='Último año en que se reseteó la secuencia'),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_journals_created_by_id_users')),
    sa.ForeignKeyConstraint(['default_account_id'], ['accounts.id'], name=op.f('fk_journals_default_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journals')),
    sa.UniqueConstraint('code', name='uq_journal_code'),
    sa.UniqueConstraint('sequence_prefix', name='uq_journal_sequence_prefix'),
    sa.UniqueConstraint('sequence_prefix', name=op.f('uq_journals_sequence_prefix'))
    )
    op.create_index(op.f('ix_journals_code'), 'journals', ['code'], unique=True)
    op.create_index(op.f('ix_journals_id'), 'journals', ['id'], unique=False)
    op.create_index(op.f('ix_journals_type'), 'journals', ['type'], unique=False)
    op.add_column('journal_entries', sa.Column('journal_id', sa.UUID(), nullable=True, comment='Diario al que pertenece este asiento'))
    op.create_index(op.f('ix_journal_entries_journal_id'), 'journal_entries', ['journal_id'], unique=False)
    op.create_foreign_key(op.f('fk_journal_entries_journal_id_journals'), 'journal_entries', 'journals', ['journal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_journal_entries_journal_id_journals'), 'journal_entries', type_='foreignkey')
    op.drop_index(op.f('ix_journal_entries_journal_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'journal_id')
    op.drop_index(op.f('ix_journals_type'), table_name='journals')
    op.drop_index(op.f('ix_journals_id'), table_name='journals')
    op.drop_index(op.f('ix_journals_code'), table_name='journals')
    op.drop_table('journals')
    # ### end Alembic commands ###