"""update_product_default_values_and_make_accounts_optional

Revision ID: 909a28c236c4
Revises: fe1aa7b28c94
Create Date: 2025-06-15 19:28:01.374422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909a28c236c4'
down_revision: Union[str, None] = 'fe1aa7b28c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Primero actualizar registros existentes con valores por defecto
    op.execute("UPDATE products SET purchase_price = 0 WHERE purchase_price IS NULL")
    op.execute("UPDATE products SET sale_price = 0 WHERE sale_price IS NULL")
    op.execute("UPDATE products SET min_sale_price = 0 WHERE min_sale_price IS NULL")
    op.execute("UPDATE products SET suggested_price = 0 WHERE suggested_price IS NULL")
    op.execute("UPDATE products SET tax_rate = 0 WHERE tax_rate IS NULL")
    op.execute("UPDATE products SET current_stock = 0 WHERE current_stock IS NULL")
    op.execute("UPDATE products SET min_stock = 0 WHERE min_stock IS NULL")
    op.execute("UPDATE products SET max_stock = 0 WHERE max_stock IS NULL")
    op.execute("UPDATE products SET reorder_point = 0 WHERE reorder_point IS NULL")
    
    # Cambiar la categoría fiscal por defecto de 'STANDARD_RATE' a 'EXEMPT'
    op.execute("UPDATE products SET tax_category = 'EXEMPT' WHERE tax_category = 'STANDARD_RATE'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'purchase_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               server_default='0',
               existing_comment='Precio de compra')
    op.alter_column('products', 'sale_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               server_default='0',
               existing_comment='Precio de venta')
    op.alter_column('products', 'min_sale_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               server_default='0',
               existing_comment='Precio mínimo de venta')
    op.alter_column('products', 'suggested_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               server_default='0',
               existing_comment='Precio sugerido')
    op.alter_column('products', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               server_default='0',
               existing_comment='Tasa de impuesto aplicable (%)')
    op.alter_column('products', 'current_stock',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               server_default='0',
               existing_comment='Stock actual')
    op.alter_column('products', 'min_stock',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               server_default='0',
               existing_comment='Stock mínimo')
    op.alter_column('products', 'max_stock',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               server_default='0',
               existing_comment='Stock máximo')
    op.alter_column('products', 'reorder_point',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=False,
               server_default='0',
               existing_comment='Punto de reorden')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'reorder_point',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               server_default=None,
               existing_comment='Punto de reorden')
    op.alter_column('products', 'max_stock',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               server_default=None,
               existing_comment='Stock máximo')
    op.alter_column('products', 'min_stock',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               server_default=None,
               existing_comment='Stock mínimo')
    op.alter_column('products', 'current_stock',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               server_default=None,
               existing_comment='Stock actual')
    op.alter_column('products', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               server_default=None,
               existing_comment='Tasa de impuesto aplicable (%)')
    op.alter_column('products', 'suggested_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               server_default=None,
               existing_comment='Precio sugerido')
    op.alter_column('products', 'min_sale_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               server_default=None,
               existing_comment='Precio mínimo de venta')
    op.alter_column('products', 'sale_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               server_default=None,
               existing_comment='Precio de venta')
    op.alter_column('products', 'purchase_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               server_default=None,
               existing_comment='Precio de compra')
    op.alter_column('products', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_comment='Tasa de impuesto aplicable (%)')
    op.alter_column('products', 'suggested_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               existing_comment='Precio sugerido')
    op.alter_column('products', 'min_sale_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               existing_comment='Precio mínimo de venta')
    op.alter_column('products', 'sale_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               existing_comment='Precio de venta')
    op.alter_column('products', 'purchase_price',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               nullable=True,
               existing_comment='Precio de compra')
    # ### end Alembic commands ###