"""Add audit fields to invoice_lines

Revision ID: a7abd97d48c9
Revises: e911fe2adf2a
Create Date: 2025-06-23 10:28:01.453219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7abd97d48c9'
down_revision: Union[str, None] = 'e911fe2adf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_lines', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.add_column('invoice_lines', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_invoice_lines_created_by_id_users'), 'invoice_lines', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_invoice_lines_updated_by_id_users'), 'invoice_lines', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invoice_lines_updated_by_id_users'), 'invoice_lines', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoice_lines_created_by_id_users'), 'invoice_lines', type_='foreignkey')
    op.drop_column('invoice_lines', 'updated_by_id')
    op.drop_column('invoice_lines', 'created_by_id')
    # ### end Alembic commands ###