"""add_payment_terms_and_invoice_dates

Revision ID: e947d2ee609f
Revises: fccd31fddf68
Create Date: 2025-06-14 22:17:22.599955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e947d2ee609f'
down_revision: Union[str, None] = 'fccd31fddf68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry_lines', sa.Column('invoice_date', sa.Date(), nullable=True, comment='Fecha de la factura (diferente a fecha de creación del asiento)'))
    op.add_column('journal_entry_lines', sa.Column('due_date', sa.Date(), nullable=True, comment='Fecha de vencimiento de la factura'))
    op.add_column('journal_entry_lines', sa.Column('payment_terms_id', sa.UUID(), nullable=True, comment='Condiciones de pago aplicables a esta línea'))
    # Comentamos la foreign key por ahora, se agregará después de crear la tabla payment_terms
    # op.create_foreign_key(op.f('fk_journal_entry_lines_payment_terms_id_payment_terms'), 'journal_entry_lines', 'payment_terms', ['payment_terms_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Comentamos porque no se creó la foreign key en upgrade
    # op.drop_constraint(op.f('fk_journal_entry_lines_payment_terms_id_payment_terms'), 'journal_entry_lines', type_='foreignkey')
    op.drop_column('journal_entry_lines', 'payment_terms_id')
    op.drop_column('journal_entry_lines', 'due_date')
    op.drop_column('journal_entry_lines', 'invoice_date')
    # ### end Alembic commands ###