"""add_unique_constraint_to_product_and_third_party_names

Revision ID: fe1aa7b28c94
Revises: 5276555e3ecf
Create Date: 2025-06-15 17:46:49.208248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1aa7b28c94'
down_revision: Union[str, None] = '5276555e3ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Nombre único del producto (case-sensitive)',
               existing_comment='Nombre del producto',
               existing_nullable=False)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.drop_index(op.f('ix_third_parties_name'), table_name='third_parties')
    op.create_index(op.f('ix_third_parties_name'), 'third_parties', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_third_parties_name'), table_name='third_parties')
    op.create_index(op.f('ix_third_parties_name'), 'third_parties', ['name'], unique=False)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Nombre del producto',
               existing_comment='Nombre único del producto (case-sensitive)',
               existing_nullable=False)
    # ### end Alembic commands ###